// Decompiled with JetBrains decompiler
// Type: WindowCenteringHelper.UI
// Assembly: WindowCenteringHelper, Version=1.2.11.0, Culture=neutral, PublicKeyToken=null
// MVID: 439D2995-1A6B-4F70-A86B-40450458C382
// Assembly location: D:\OneDrive - 薅羊毛大学\下载\WindowCenteringHelper_new\Release\WindowCenteringHelper.exe

using KamilSzymborski.WindowCenteringHelper.Core;
using MetroFramework;
using MetroFramework.Controls;
using MetroFramework.Drawing;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace WindowCenteringHelper
{
  public class UI : Form
  {
    private readonly Config Cfg;
    private readonly CenteringHelper _Core;
    private IContainer components;
    private Panel panel1;
    private MetroPanel metroPanel8;
    private MetroPanel metroPanel1;
    private MetroPanel metroPanel6;
    private LinkLabel linkLabel2;
    private MetroPanel metroPanel5;
    private System.Windows.Forms.Label label28;
    private System.Windows.Forms.Label label29;
    private MetroPanel metroPanel4;
    private System.Windows.Forms.Label label26;
    private System.Windows.Forms.Label label27;
    private System.Windows.Forms.Label label24;
    private System.Windows.Forms.Label label25;
    private System.Windows.Forms.Label label23;
    private System.Windows.Forms.Label label22;
    private System.Windows.Forms.Label label30;
    private MetroPanel metroPanel12;
    private Panel panel3;
    private MetroTrackBar metroTrackBar4;
    private System.Windows.Forms.Label label6;
    private MetroPanel metroPanel20;
    private Panel panel10;
    private MetroTrackBar metroTrackBar5;
    private System.Windows.Forms.Label label20;
    private MetroPanel metroPanel14;
    private Panel panel13;
    private MetroTrackBar metroTrackBar2;
    private System.Windows.Forms.Label label21;
    private System.Windows.Forms.Label label5;
    private MetroPanel metroPanel3;
    private TableLayoutPanel tableLayoutPanel3;
    private MetroToggle metroToggle9;
    private Panel panel8;
    private System.Windows.Forms.Label label19;
    private MetroPanel metroPanel2;
    private TableLayoutPanel tableLayoutPanel10;
    private MetroToggle metroToggle8;
    private Panel panel7;
    private System.Windows.Forms.Label label17;
    private MetroPanel metroPanel7;
    private TableLayoutPanel tableLayoutPanel5;
    private MetroToggle metroToggle5;
    private Panel panel5;
    private System.Windows.Forms.Label label14;
    private System.Windows.Forms.Label label10;
    private MetroPanel metroPanel16;
    private TableLayoutPanel tableLayoutPanel6;
    private MetroToggle metroToggle6;
    private Panel panel6;
    private System.Windows.Forms.Label label12;
    private MetroPanel metroPanel17;
    private TableLayoutPanel tableLayoutPanel7;
    private MetroToggle metroToggle7;
    private Panel panel9;
    private MetroTrackBar metroTrackBar3;
    private System.Windows.Forms.Label label8;
    private MetroPanel metroPanel15;
    private TableLayoutPanel tableLayoutPanel4;
    private MetroToggle metroToggle4;
    private Panel panel4;
    private MetroTrackBar metroTrackBar1;
    private System.Windows.Forms.Label label15;
    private TableLayoutPanel tableLayoutPanel9;
    private TableLayoutPanel tableLayoutPanel8;
    private System.Windows.Forms.Label label9;
    private MetroPanel metroPanel10;
    private TableLayoutPanel tableLayoutPanel2;
    private MetroToggle metroToggle2;
    private Panel panel11;
    private System.Windows.Forms.Label label3;
    private System.Windows.Forms.Label label4;
    private MetroPanel metroPanel9;
    private TableLayoutPanel tableLayoutPanel12;
    private MetroProgressBar metroProgressBar5;
    private MetroToggle metroToggle1;
    private Panel panel12;
    private System.Windows.Forms.Label label2;
    private System.Windows.Forms.Label label7;
    private System.Windows.Forms.Label label1;
    private Panel panel2;
    private LinkLabel linkLabel1;
    private MetroProgressBar metroProgressBar1;

    internal UI(CenteringHelper Core, Config Cfg)
    {
      this.InitializeComponent();
      this._Core = Core;
      this.Cfg = Cfg;
      this._Init();
      this.Shown += new EventHandler(this.UI_Shown);
    }

    private void UI_Shown(object sender, EventArgs e)
    {
      this.metroToggle1.Checked = this.Cfg.ActiveServices.HasFlag((Enum) Services.Automatically);
      this.metroToggle2.Checked = this.Cfg.ActiveServices.HasFlag((Enum) Services.OnKeySequence);
      this.metroToggle4.Checked = this.Cfg.CustomWindowWidth;
      this.label15.Text = string.Format("Window width: [{0}%]", (object) this.Cfg.WindowWidth);
      this.label8.Text = string.Format("Window height: [{0}%]", (object) this.Cfg.WindowHeight);
      this.metroTrackBar1.Value = this.Cfg.WindowWidth / 2;
      this.metroToggle7.Checked = this.Cfg.CustomWindowHeight;
      this.metroTrackBar3.Value = this.Cfg.WindowHeight / 2;
      this.metroToggle6.Checked = this.Cfg.ForceToResizeWindow;
      this.metroToggle5.Checked = this.Cfg.OnlyNewWindow;
      this.metroToggle9.Checked = this.Cfg.HelpMeDecide;
      this.metroTrackBar2.Value = (int) Enum.Parse(typeof (Keys), this.Cfg.Key);
      this.label21.Text = "Key: [" + this.Cfg.Key.ToString() + "]";
      this.metroTrackBar5.Value = this.Cfg.Times;
      this.label20.Text = string.Format("Times: [{0}]", (object) this.Cfg.Times);
      this.metroTrackBar4.Value = this.Cfg.Timeout / 50;
      this.label6.Text = string.Format("Timeout: [{0} ms]", (object) this.Cfg.Timeout);
      this.metroToggle8.Checked = this.Cfg.OnlyOnPrimaryScreen;
    }

    private void _Init()
    {
      this.linkLabel1.BackColor = GlobalMetroColor.Color;
      this.linkLabel2.Click += (EventHandler) ((Instance, Arguments) => Application.Exit());
      this.linkLabel1.Click += (EventHandler) ((Instance, Arguments) => Process.Start("https://kamilszymborski.github.io"));
      this.metroToggle1.CheckedChanged += (EventHandler) ((Instance, Arguments) =>
      {
        if (this.metroToggle1.Checked)
          this.metroProgressBar5.Visible = true;
        else
          this.metroProgressBar5.Visible = false;
        Services services = Services.None;
        if (this.metroToggle1.Checked)
          services |= Services.Automatically;
        if (this.metroToggle2.Checked)
          services |= Services.OnKeySequence;
        this._Core.ActiveServices = services;
      });
      this.metroToggle2.CheckedChanged += (EventHandler) ((Instance, Arguments) =>
      {
        if (this.metroToggle2.Checked)
          this.metroProgressBar1.Visible = true;
        else
          this.metroProgressBar1.Visible = false;
        Services services = Services.None;
        if (this.metroToggle1.Checked)
          services |= Services.Automatically;
        if (this.metroToggle2.Checked)
          services |= Services.OnKeySequence;
        this._Core.ActiveServices = services;
      });
      this.metroToggle4.CheckedChanged += (EventHandler) ((Instance, Arguments) => this._Core.CustomWindowWidth = this.metroToggle4.Checked);
      this.metroTrackBar1.Maximum = 50;
      this.metroTrackBar1.ValueChanged += (EventHandler) ((Instance, Arguments) =>
      {
        this.metroTrackBar1.Style = this.metroTrackBar1.Value * 2 > 40 ? (this.metroTrackBar1.Value * 2 > 60 ? (this.metroTrackBar1.Value * 2 != 98 ? (this.metroTrackBar1.Value * 2 != 100 ? MetroColorStyle.System : MetroColorStyle.Red) : MetroColorStyle.Yellow) : MetroColorStyle.Yellow) : MetroColorStyle.Red;
        this.label15.Text = string.Format("Window width: [{0}%]", (object) (this.metroTrackBar1.Value * 2));
        this._Core.WindowWidth = (uint) (this.metroTrackBar1.Value * 2);
      });
      this.metroToggle7.CheckedChanged += (EventHandler) ((Instance, Arguments) => this._Core.CustomWindowHeight = this.metroToggle7.Checked);
      this.metroToggle8.CheckedChanged += (EventHandler) ((Instance, Arguments) => this._Core.OnlyOnPrimaryScreen = this.metroToggle8.Checked);
      this.metroTrackBar3.Maximum = 50;
      this.metroTrackBar3.ValueChanged += (EventHandler) ((Instance, Arguments) =>
      {
        this.metroTrackBar3.Style = this.metroTrackBar3.Value * 2 > 40 ? (this.metroTrackBar3.Value * 2 > 60 ? (this.metroTrackBar3.Value * 2 != 98 ? (this.metroTrackBar3.Value * 2 != 100 ? MetroColorStyle.System : MetroColorStyle.Red) : MetroColorStyle.Yellow) : MetroColorStyle.Yellow) : MetroColorStyle.Red;
        this.label8.Text = string.Format("Window height: [{0}%]", (object) (this.metroTrackBar3.Value * 2));
        this._Core.WindowHeight = (uint) (this.metroTrackBar3.Value * 2);
      });
      this.metroToggle6.CheckedChanged += (EventHandler) ((Instance, Arguments) => this._Core.ForceToResizeWindow = this.metroToggle6.Checked);
      this.metroToggle5.CheckedChanged += (EventHandler) ((Instance, Arguments) => this._Core.OnlyNewWindow = this.metroToggle5.Checked);
      this.metroToggle9.CheckedChanged += (EventHandler) ((Instance, Arguments) => this._Core.HelpMeDecide = this.metroToggle9.Checked);
      this.metroTrackBar2.Maximum = ((IEnumerable<string>) Enum.GetNames(typeof (Keys))).Count<string>();
      this.metroTrackBar2.ValueChanged += (EventHandler) ((Instance, Arguments) =>
      {
        this.label21.Text = string.Format("Key: [{0}]", (object) (Keys) this.metroTrackBar2.Value);
        this._Core.SequenceKey = (Keys) this.metroTrackBar2.Value;
      });
      this.metroTrackBar5.Maximum = 5;
      this.metroTrackBar5.ValueChanged += (EventHandler) ((Instance, Arguments) =>
      {
        this.label20.Text = string.Format("Times: [{0}]", (object) this.metroTrackBar5.Value);
        this._Core.SequenceLength = (uint) this.metroTrackBar5.Value;
      });
      this.metroTrackBar4.Maximum = 40;
      this.metroTrackBar4.Minimum = 2;
      this.metroTrackBar4.ValueChanged += (EventHandler) ((Instance, Arguments) =>
      {
        this.label6.Text = string.Format("Timeout: [{0} ms]", (object) (this.metroTrackBar4.Value * 50));
        this._Core.SequenceTimeout = (uint) (this.metroTrackBar4.Value * 50);
      });
      this.FormClosing += (FormClosingEventHandler) ((Instance, Arguments) =>
      {
        if (Arguments.CloseReason == CloseReason.UserClosing)
        {
          Arguments.Cancel = true;
          this.Hide();
        }
        else
        {
          Arguments.Cancel = false;
          this._Core.Close();
        }
      });
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (UI));
      this.panel1 = new Panel();
      this.metroPanel8 = new MetroPanel();
      this.metroPanel1 = new MetroPanel();
      this.metroPanel6 = new MetroPanel();
      this.linkLabel2 = new LinkLabel();
      this.metroPanel5 = new MetroPanel();
      this.label28 = new System.Windows.Forms.Label();
      this.label29 = new System.Windows.Forms.Label();
      this.metroPanel4 = new MetroPanel();
      this.label26 = new System.Windows.Forms.Label();
      this.label27 = new System.Windows.Forms.Label();
      this.label24 = new System.Windows.Forms.Label();
      this.label25 = new System.Windows.Forms.Label();
      this.label23 = new System.Windows.Forms.Label();
      this.label22 = new System.Windows.Forms.Label();
      this.label30 = new System.Windows.Forms.Label();
      this.metroPanel12 = new MetroPanel();
      this.panel3 = new Panel();
      this.metroTrackBar4 = new MetroTrackBar();
      this.label6 = new System.Windows.Forms.Label();
      this.metroPanel20 = new MetroPanel();
      this.panel10 = new Panel();
      this.metroTrackBar5 = new MetroTrackBar();
      this.label20 = new System.Windows.Forms.Label();
      this.metroPanel14 = new MetroPanel();
      this.panel13 = new Panel();
      this.metroTrackBar2 = new MetroTrackBar();
      this.label21 = new System.Windows.Forms.Label();
      this.label5 = new System.Windows.Forms.Label();
      this.metroPanel3 = new MetroPanel();
      this.tableLayoutPanel3 = new TableLayoutPanel();
      this.metroToggle9 = new MetroToggle();
      this.panel8 = new Panel();
      this.label19 = new System.Windows.Forms.Label();
      this.metroPanel2 = new MetroPanel();
      this.tableLayoutPanel10 = new TableLayoutPanel();
      this.metroToggle8 = new MetroToggle();
      this.panel7 = new Panel();
      this.label17 = new System.Windows.Forms.Label();
      this.metroPanel7 = new MetroPanel();
      this.tableLayoutPanel5 = new TableLayoutPanel();
      this.metroToggle5 = new MetroToggle();
      this.panel5 = new Panel();
      this.label14 = new System.Windows.Forms.Label();
      this.label10 = new System.Windows.Forms.Label();
      this.metroPanel16 = new MetroPanel();
      this.tableLayoutPanel6 = new TableLayoutPanel();
      this.metroToggle6 = new MetroToggle();
      this.panel6 = new Panel();
      this.label12 = new System.Windows.Forms.Label();
      this.metroPanel17 = new MetroPanel();
      this.tableLayoutPanel7 = new TableLayoutPanel();
      this.metroToggle7 = new MetroToggle();
      this.panel9 = new Panel();
      this.metroTrackBar3 = new MetroTrackBar();
      this.label8 = new System.Windows.Forms.Label();
      this.metroPanel15 = new MetroPanel();
      this.tableLayoutPanel4 = new TableLayoutPanel();
      this.metroToggle4 = new MetroToggle();
      this.panel4 = new Panel();
      this.metroTrackBar1 = new MetroTrackBar();
      this.label15 = new System.Windows.Forms.Label();
      this.tableLayoutPanel9 = new TableLayoutPanel();
      this.tableLayoutPanel8 = new TableLayoutPanel();
      this.label9 = new System.Windows.Forms.Label();
      this.metroPanel10 = new MetroPanel();
      this.tableLayoutPanel2 = new TableLayoutPanel();
      this.metroProgressBar1 = new MetroProgressBar();
      this.metroToggle2 = new MetroToggle();
      this.panel11 = new Panel();
      this.label3 = new System.Windows.Forms.Label();
      this.label4 = new System.Windows.Forms.Label();
      this.metroPanel9 = new MetroPanel();
      this.tableLayoutPanel12 = new TableLayoutPanel();
      this.metroProgressBar5 = new MetroProgressBar();
      this.metroToggle1 = new MetroToggle();
      this.panel12 = new Panel();
      this.label2 = new System.Windows.Forms.Label();
      this.label7 = new System.Windows.Forms.Label();
      this.label1 = new System.Windows.Forms.Label();
      this.panel2 = new Panel();
      this.linkLabel1 = new LinkLabel();
      this.panel1.SuspendLayout();
      this.metroPanel8.SuspendLayout();
      this.metroPanel1.SuspendLayout();
      this.panel3.SuspendLayout();
      this.panel10.SuspendLayout();
      this.panel13.SuspendLayout();
      this.tableLayoutPanel3.SuspendLayout();
      this.panel8.SuspendLayout();
      this.tableLayoutPanel10.SuspendLayout();
      this.panel7.SuspendLayout();
      this.tableLayoutPanel5.SuspendLayout();
      this.panel5.SuspendLayout();
      this.tableLayoutPanel6.SuspendLayout();
      this.panel6.SuspendLayout();
      this.tableLayoutPanel7.SuspendLayout();
      this.panel9.SuspendLayout();
      this.tableLayoutPanel4.SuspendLayout();
      this.panel4.SuspendLayout();
      this.tableLayoutPanel2.SuspendLayout();
      this.panel11.SuspendLayout();
      this.tableLayoutPanel12.SuspendLayout();
      this.panel12.SuspendLayout();
      this.SuspendLayout();
      this.panel1.Controls.Add((Control) this.metroPanel8);
      this.panel1.Controls.Add((Control) this.linkLabel1);
      this.panel1.Dock = DockStyle.Fill;
      this.panel1.Location = new Point(0, 0);
      this.panel1.Margin = new Padding(0);
      this.panel1.Name = "panel1";
      this.panel1.Size = new Size(604, 685);
      this.panel1.TabIndex = 1;
      this.metroPanel8.AutoScroll = true;
      this.metroPanel8.Controls.Add((Control) this.metroPanel1);
      this.metroPanel8.Controls.Add((Control) this.label30);
      this.metroPanel8.Controls.Add((Control) this.metroPanel12);
      this.metroPanel8.Controls.Add((Control) this.panel3);
      this.metroPanel8.Controls.Add((Control) this.metroPanel20);
      this.metroPanel8.Controls.Add((Control) this.panel10);
      this.metroPanel8.Controls.Add((Control) this.metroPanel14);
      this.metroPanel8.Controls.Add((Control) this.panel13);
      this.metroPanel8.Controls.Add((Control) this.label5);
      this.metroPanel8.Controls.Add((Control) this.metroPanel3);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel3);
      this.metroPanel8.Controls.Add((Control) this.metroPanel2);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel10);
      this.metroPanel8.Controls.Add((Control) this.metroPanel7);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel5);
      this.metroPanel8.Controls.Add((Control) this.label10);
      this.metroPanel8.Controls.Add((Control) this.metroPanel16);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel6);
      this.metroPanel8.Controls.Add((Control) this.metroPanel17);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel7);
      this.metroPanel8.Controls.Add((Control) this.metroPanel15);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel4);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel9);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel8);
      this.metroPanel8.Controls.Add((Control) this.label9);
      this.metroPanel8.Controls.Add((Control) this.metroPanel10);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel2);
      this.metroPanel8.Controls.Add((Control) this.metroPanel9);
      this.metroPanel8.Controls.Add((Control) this.tableLayoutPanel12);
      this.metroPanel8.Controls.Add((Control) this.label1);
      this.metroPanel8.Controls.Add((Control) this.panel2);
      this.metroPanel8.Dock = DockStyle.Fill;
      this.metroPanel8.HorizontalScrollbar = true;
      this.metroPanel8.HorizontalScrollbarBarColor = true;
      this.metroPanel8.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel8.HorizontalScrollbarSize = 10;
      this.metroPanel8.Location = new Point(0, 0);
      this.metroPanel8.Name = "metroPanel8";
      this.metroPanel8.Padding = new Padding(15, 0, 15, 0);
      this.metroPanel8.Size = new Size(604, 664);
      this.metroPanel8.Style = MetroColorStyle.Teal;
      this.metroPanel8.TabIndex = 112;
      this.metroPanel8.UseStyleColors = true;
      this.metroPanel8.VerticalScrollbar = true;
      this.metroPanel8.VerticalScrollbarBarColor = true;
      this.metroPanel8.VerticalScrollbarHighlightOnWheel = true;
      this.metroPanel8.VerticalScrollbarSize = 4;
      this.metroPanel1.AutoSize = true;
      this.metroPanel1.Controls.Add((Control) this.metroPanel6);
      this.metroPanel1.Controls.Add((Control) this.linkLabel2);
      this.metroPanel1.Controls.Add((Control) this.metroPanel5);
      this.metroPanel1.Controls.Add((Control) this.label28);
      this.metroPanel1.Controls.Add((Control) this.label29);
      this.metroPanel1.Controls.Add((Control) this.metroPanel4);
      this.metroPanel1.Controls.Add((Control) this.label26);
      this.metroPanel1.Controls.Add((Control) this.label27);
      this.metroPanel1.Controls.Add((Control) this.label24);
      this.metroPanel1.Controls.Add((Control) this.label25);
      this.metroPanel1.Controls.Add((Control) this.label23);
      this.metroPanel1.Controls.Add((Control) this.label22);
      this.metroPanel1.Dock = DockStyle.Top;
      this.metroPanel1.HorizontalScrollbarBarColor = true;
      this.metroPanel1.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel1.HorizontalScrollbarSize = 9;
      this.metroPanel1.Location = new Point(15, 874);
      this.metroPanel1.Margin = new Padding(0);
      this.metroPanel1.Name = "metroPanel1";
      this.metroPanel1.Size = new Size(548, 202);
      this.metroPanel1.TabIndex = 109;
      this.metroPanel1.VerticalScrollbarBarColor = true;
      this.metroPanel1.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel1.VerticalScrollbarSize = 10;
      this.metroPanel6.Dock = DockStyle.Top;
      this.metroPanel6.HorizontalScrollbarBarColor = true;
      this.metroPanel6.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel6.HorizontalScrollbarSize = 9;
      this.metroPanel6.Location = new Point(0, 187);
      this.metroPanel6.Name = "metroPanel6";
      this.metroPanel6.Size = new Size(548, 15);
      this.metroPanel6.TabIndex = 115;
      this.metroPanel6.VerticalScrollbarBarColor = true;
      this.metroPanel6.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel6.VerticalScrollbarSize = 10;
      this.linkLabel2.ActiveLinkColor = Color.White;
      this.linkLabel2.AutoSize = true;
      this.linkLabel2.BackColor = Color.Crimson;
      this.linkLabel2.Dock = DockStyle.Top;
      this.linkLabel2.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.linkLabel2.ForeColor = Color.White;
      this.linkLabel2.LinkBehavior = LinkBehavior.NeverUnderline;
      this.linkLabel2.LinkColor = Color.White;
      this.linkLabel2.Location = new Point(0, 166);
      this.linkLabel2.Name = "linkLabel2";
      this.linkLabel2.Padding = new Padding(4, 2, 4, 2);
      this.linkLabel2.Size = new Size(203, 21);
      this.linkLabel2.TabIndex = 114;
      this.linkLabel2.TabStop = true;
      this.linkLabel2.Text = "Terminate services and Close";
      this.metroPanel5.Dock = DockStyle.Top;
      this.metroPanel5.HorizontalScrollbarBarColor = true;
      this.metroPanel5.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel5.HorizontalScrollbarSize = 9;
      this.metroPanel5.Location = new Point(0, 151);
      this.metroPanel5.Name = "metroPanel5";
      this.metroPanel5.Size = new Size(548, 15);
      this.metroPanel5.TabIndex = 113;
      this.metroPanel5.VerticalScrollbarBarColor = true;
      this.metroPanel5.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel5.VerticalScrollbarSize = 10;
      this.label28.AutoSize = true;
      this.label28.Dock = DockStyle.Top;
      this.label28.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label28.Location = new Point(0, 134);
      this.label28.Name = "label28";
      this.label28.Size = new Size(132, 17);
      this.label28.TabIndex = 112;
      this.label28.Text = "George Mamaladze";
      this.label29.AutoSize = true;
      this.label29.Dock = DockStyle.Top;
      this.label29.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label29.ForeColor = SystemColors.ControlDarkDark;
      this.label29.Location = new Point(0, 117);
      this.label29.Name = "label29";
      this.label29.Size = new Size(107, 17);
      this.label29.TabIndex = 111;
      this.label29.Text = "MouseKeyHook";
      this.metroPanel4.Dock = DockStyle.Top;
      this.metroPanel4.HorizontalScrollbarBarColor = true;
      this.metroPanel4.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel4.HorizontalScrollbarSize = 9;
      this.metroPanel4.Location = new Point(0, 102);
      this.metroPanel4.Name = "metroPanel4";
      this.metroPanel4.Size = new Size(548, 15);
      this.metroPanel4.TabIndex = 110;
      this.metroPanel4.VerticalScrollbarBarColor = true;
      this.metroPanel4.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel4.VerticalScrollbarSize = 10;
      this.label26.AutoSize = true;
      this.label26.Dock = DockStyle.Top;
      this.label26.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label26.Location = new Point(0, 85);
      this.label26.Name = "label26";
      this.label26.Size = new Size(118, 17);
      this.label26.TabIndex = 109;
      this.label26.Text = "Kamil Szymborski";
      this.label27.AutoSize = true;
      this.label27.Dock = DockStyle.Top;
      this.label27.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label27.ForeColor = SystemColors.ControlDarkDark;
      this.label27.Location = new Point(0, 68);
      this.label27.Name = "label27";
      this.label27.Size = new Size(49, 17);
      this.label27.TabIndex = 108;
      this.label27.Text = "author";
      this.label24.AutoSize = true;
      this.label24.Dock = DockStyle.Top;
      this.label24.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label24.Location = new Point(0, 51);
      this.label24.Name = "label24";
      this.label24.Size = new Size(67, 17);
      this.label24.TabIndex = 107;
      this.label24.Text = "Freeware";
      this.label25.AutoSize = true;
      this.label25.Dock = DockStyle.Top;
      this.label25.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label25.ForeColor = SystemColors.ControlDarkDark;
      this.label25.Location = new Point(0, 34);
      this.label25.Name = "label25";
      this.label25.Size = new Size(52, 17);
      this.label25.TabIndex = 106;
      this.label25.Text = "license";
      this.label23.AutoSize = true;
      this.label23.Dock = DockStyle.Top;
      this.label23.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label23.Location = new Point(0, 17);
      this.label23.Name = "label23";
      this.label23.Size = new Size(43, 17);
      this.label23.TabIndex = 5;
      this.label23.Text = "-------";
      this.label22.AutoSize = true;
      this.label22.Dock = DockStyle.Top;
      this.label22.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label22.ForeColor = SystemColors.ControlDarkDark;
      this.label22.Location = new Point(0, 0);
      this.label22.Name = "label22";
      this.label22.Size = new Size(32, 17);
      this.label22.TabIndex = 4;
      this.label22.Text = "ver.";
      this.label30.Dock = DockStyle.Top;
      this.label30.ForeColor = SystemColors.ControlDarkDark;
      this.label30.Location = new Point(15, 854);
      this.label30.Name = "label30";
      this.label30.Size = new Size(548, 20);
      this.label30.TabIndex = 108;
      this.label30.Text = "About";
      this.label30.TextAlign = ContentAlignment.MiddleCenter;
      this.metroPanel12.Dock = DockStyle.Top;
      this.metroPanel12.HorizontalScrollbarBarColor = true;
      this.metroPanel12.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel12.HorizontalScrollbarSize = 9;
      this.metroPanel12.Location = new Point(15, 839);
      this.metroPanel12.Name = "metroPanel12";
      this.metroPanel12.Size = new Size(548, 15);
      this.metroPanel12.TabIndex = 105;
      this.metroPanel12.VerticalScrollbarBarColor = true;
      this.metroPanel12.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel12.VerticalScrollbarSize = 10;
      this.panel3.AutoSize = true;
      this.panel3.BackColor = Color.White;
      this.panel3.Controls.Add((Control) this.metroTrackBar4);
      this.panel3.Controls.Add((Control) this.label6);
      this.panel3.Dock = DockStyle.Top;
      this.panel3.Location = new Point(15, 793);
      this.panel3.Name = "panel3";
      this.panel3.Padding = new Padding(3);
      this.panel3.Size = new Size(548, 46);
      this.panel3.TabIndex = 99;
      this.metroTrackBar4.BackColor = Color.Transparent;
      this.metroTrackBar4.Dock = DockStyle.Top;
      this.metroTrackBar4.Location = new Point(3, 20);
      this.metroTrackBar4.Maximum = 2200;
      this.metroTrackBar4.Minimum = 1;
      this.metroTrackBar4.Name = "metroTrackBar4";
      this.metroTrackBar4.Size = new Size(542, 23);
      this.metroTrackBar4.Style = MetroColorStyle.System;
      this.metroTrackBar4.TabIndex = 6;
      this.metroTrackBar4.TabStop = false;
      this.metroTrackBar4.Text = "metroTrackBar4";
      this.metroTrackBar4.Theme = MetroThemeStyle.Dark;
      this.metroTrackBar4.Value = 65;
      this.label6.AutoSize = true;
      this.label6.Dock = DockStyle.Top;
      this.label6.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label6.Location = new Point(3, 3);
      this.label6.Name = "label6";
      this.label6.Size = new Size(129, 17);
      this.label6.TabIndex = 2;
      this.label6.Text = "Timeout: [1200 ms]";
      this.metroPanel20.Dock = DockStyle.Top;
      this.metroPanel20.HorizontalScrollbarBarColor = true;
      this.metroPanel20.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel20.HorizontalScrollbarSize = 9;
      this.metroPanel20.Location = new Point(15, 778);
      this.metroPanel20.Name = "metroPanel20";
      this.metroPanel20.Size = new Size(548, 15);
      this.metroPanel20.TabIndex = 104;
      this.metroPanel20.VerticalScrollbarBarColor = true;
      this.metroPanel20.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel20.VerticalScrollbarSize = 10;
      this.panel10.AutoSize = true;
      this.panel10.BackColor = Color.White;
      this.panel10.Controls.Add((Control) this.metroTrackBar5);
      this.panel10.Controls.Add((Control) this.label20);
      this.panel10.Dock = DockStyle.Top;
      this.panel10.Location = new Point(15, 732);
      this.panel10.Name = "panel10";
      this.panel10.Padding = new Padding(3);
      this.panel10.Size = new Size(548, 46);
      this.panel10.TabIndex = 103;
      this.metroTrackBar5.BackColor = Color.Transparent;
      this.metroTrackBar5.Dock = DockStyle.Top;
      this.metroTrackBar5.Location = new Point(3, 20);
      this.metroTrackBar5.Minimum = 1;
      this.metroTrackBar5.Name = "metroTrackBar5";
      this.metroTrackBar5.Size = new Size(542, 23);
      this.metroTrackBar5.Style = MetroColorStyle.System;
      this.metroTrackBar5.TabIndex = 6;
      this.metroTrackBar5.TabStop = false;
      this.metroTrackBar5.Text = "metroTrackBar5";
      this.metroTrackBar5.Theme = MetroThemeStyle.Dark;
      this.metroTrackBar5.Value = 73;
      this.label20.AutoSize = true;
      this.label20.Dock = DockStyle.Top;
      this.label20.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label20.Location = new Point(3, 3);
      this.label20.Name = "label20";
      this.label20.Size = new Size(70, 17);
      this.label20.TabIndex = 2;
      this.label20.Text = "Times: [3]";
      this.metroPanel14.Dock = DockStyle.Top;
      this.metroPanel14.HorizontalScrollbarBarColor = true;
      this.metroPanel14.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel14.HorizontalScrollbarSize = 9;
      this.metroPanel14.Location = new Point(15, 717);
      this.metroPanel14.Name = "metroPanel14";
      this.metroPanel14.Size = new Size(548, 15);
      this.metroPanel14.TabIndex = 102;
      this.metroPanel14.VerticalScrollbarBarColor = true;
      this.metroPanel14.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel14.VerticalScrollbarSize = 10;
      this.panel13.AutoSize = true;
      this.panel13.BackColor = Color.White;
      this.panel13.Controls.Add((Control) this.metroTrackBar2);
      this.panel13.Controls.Add((Control) this.label21);
      this.panel13.Dock = DockStyle.Top;
      this.panel13.Location = new Point(15, 671);
      this.panel13.Name = "panel13";
      this.panel13.Padding = new Padding(3);
      this.panel13.Size = new Size(548, 46);
      this.panel13.TabIndex = 101;
      this.metroTrackBar2.BackColor = Color.Transparent;
      this.metroTrackBar2.Dock = DockStyle.Top;
      this.metroTrackBar2.Location = new Point(3, 20);
      this.metroTrackBar2.Maximum = 700;
      this.metroTrackBar2.Minimum = 1;
      this.metroTrackBar2.Name = "metroTrackBar2";
      this.metroTrackBar2.Size = new Size(542, 23);
      this.metroTrackBar2.Style = MetroColorStyle.System;
      this.metroTrackBar2.TabIndex = 6;
      this.metroTrackBar2.TabStop = false;
      this.metroTrackBar2.Text = "metroTrackBar2";
      this.metroTrackBar2.Theme = MetroThemeStyle.Dark;
      this.metroTrackBar2.Value = 33;
      this.label21.AutoSize = true;
      this.label21.Dock = DockStyle.Top;
      this.label21.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label21.Location = new Point(3, 3);
      this.label21.Name = "label21";
      this.label21.Size = new Size(77, 17);
      this.label21.TabIndex = 2;
      this.label21.Text = "Key: [lshift]";
      this.label5.Dock = DockStyle.Top;
      this.label5.ForeColor = SystemColors.ControlDarkDark;
      this.label5.Location = new Point(15, 651);
      this.label5.Name = "label5";
      this.label5.Size = new Size(548, 20);
      this.label5.TabIndex = 95;
      this.label5.Text = "On Key Sequence";
      this.label5.TextAlign = ContentAlignment.MiddleCenter;
      this.metroPanel3.Dock = DockStyle.Top;
      this.metroPanel3.HorizontalScrollbarBarColor = true;
      this.metroPanel3.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel3.HorizontalScrollbarSize = 9;
      this.metroPanel3.Location = new Point(15, 636);
      this.metroPanel3.Name = "metroPanel3";
      this.metroPanel3.Size = new Size(548, 15);
      this.metroPanel3.TabIndex = 94;
      this.metroPanel3.VerticalScrollbarBarColor = true;
      this.metroPanel3.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel3.VerticalScrollbarSize = 10;
      this.tableLayoutPanel3.AutoSize = true;
      this.tableLayoutPanel3.ColumnCount = 1;
      this.tableLayoutPanel3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel3.Controls.Add((Control) this.metroToggle9, 0, 0);
      this.tableLayoutPanel3.Controls.Add((Control) this.panel8, 0, 1);
      this.tableLayoutPanel3.Dock = DockStyle.Top;
      this.tableLayoutPanel3.Location = new Point(15, 591);
      this.tableLayoutPanel3.Name = "tableLayoutPanel3";
      this.tableLayoutPanel3.RowCount = 2;
      this.tableLayoutPanel3.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel3.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel3.Size = new Size(548, 45);
      this.tableLayoutPanel3.TabIndex = 93;
      this.metroToggle9.Checked = true;
      this.metroToggle9.CheckState = CheckState.Checked;
      this.metroToggle9.DisplayStatus = false;
      this.metroToggle9.Location = new Point(3, 3);
      this.metroToggle9.Name = "metroToggle9";
      this.metroToggle9.Size = new Size(22, 10);
      this.metroToggle9.Style = MetroColorStyle.System;
      this.metroToggle9.TabIndex = 0;
      this.metroToggle9.Text = "On";
      this.metroToggle9.Theme = MetroThemeStyle.Dark;
      this.metroToggle9.UseSelectable = true;
      this.panel8.AutoSize = true;
      this.panel8.BackColor = Color.White;
      this.panel8.Controls.Add((Control) this.label19);
      this.panel8.Dock = DockStyle.Top;
      this.panel8.Location = new Point(3, 19);
      this.panel8.Name = "panel8";
      this.panel8.Padding = new Padding(3);
      this.panel8.Size = new Size(542, 23);
      this.panel8.TabIndex = 1;
      this.label19.AutoSize = true;
      this.label19.Dock = DockStyle.Top;
      this.label19.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label19.Location = new Point(3, 3);
      this.label19.Name = "label19";
      this.label19.Size = new Size(320, 17);
      this.label19.TabIndex = 2;
      this.label19.Text = "Help me decide which window should be excluded";
      this.metroPanel2.Dock = DockStyle.Top;
      this.metroPanel2.HorizontalScrollbarBarColor = true;
      this.metroPanel2.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel2.HorizontalScrollbarSize = 9;
      this.metroPanel2.Location = new Point(15, 576);
      this.metroPanel2.Name = "metroPanel2";
      this.metroPanel2.Size = new Size(548, 15);
      this.metroPanel2.TabIndex = 92;
      this.metroPanel2.VerticalScrollbarBarColor = true;
      this.metroPanel2.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel2.VerticalScrollbarSize = 10;
      this.tableLayoutPanel10.AutoSize = true;
      this.tableLayoutPanel10.ColumnCount = 1;
      this.tableLayoutPanel10.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel10.Controls.Add((Control) this.metroToggle8, 0, 0);
      this.tableLayoutPanel10.Controls.Add((Control) this.panel7, 0, 1);
      this.tableLayoutPanel10.Dock = DockStyle.Top;
      this.tableLayoutPanel10.Location = new Point(15, 531);
      this.tableLayoutPanel10.Name = "tableLayoutPanel10";
      this.tableLayoutPanel10.RowCount = 2;
      this.tableLayoutPanel10.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel10.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel10.Size = new Size(548, 45);
      this.tableLayoutPanel10.TabIndex = 89;
      this.metroToggle8.DisplayStatus = false;
      this.metroToggle8.Location = new Point(3, 3);
      this.metroToggle8.Name = "metroToggle8";
      this.metroToggle8.Size = new Size(22, 10);
      this.metroToggle8.Style = MetroColorStyle.System;
      this.metroToggle8.TabIndex = 0;
      this.metroToggle8.Text = "Off";
      this.metroToggle8.Theme = MetroThemeStyle.Dark;
      this.metroToggle8.UseSelectable = true;
      this.panel7.AutoSize = true;
      this.panel7.BackColor = Color.White;
      this.panel7.Controls.Add((Control) this.label17);
      this.panel7.Dock = DockStyle.Top;
      this.panel7.Location = new Point(3, 19);
      this.panel7.Name = "panel7";
      this.panel7.Padding = new Padding(3);
      this.panel7.Size = new Size(542, 23);
      this.panel7.TabIndex = 1;
      this.label17.AutoSize = true;
      this.label17.Dock = DockStyle.Top;
      this.label17.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label17.Location = new Point(3, 3);
      this.label17.Name = "label17";
      this.label17.Size = new Size(155, 17);
      this.label17.TabIndex = 2;
      this.label17.Text = "Only on primary screen";
      this.metroPanel7.Dock = DockStyle.Top;
      this.metroPanel7.HorizontalScrollbarBarColor = true;
      this.metroPanel7.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel7.HorizontalScrollbarSize = 9;
      this.metroPanel7.Location = new Point(15, 516);
      this.metroPanel7.Name = "metroPanel7";
      this.metroPanel7.Size = new Size(548, 15);
      this.metroPanel7.TabIndex = 88;
      this.metroPanel7.VerticalScrollbarBarColor = true;
      this.metroPanel7.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel7.VerticalScrollbarSize = 10;
      this.tableLayoutPanel5.AutoSize = true;
      this.tableLayoutPanel5.ColumnCount = 1;
      this.tableLayoutPanel5.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel5.Controls.Add((Control) this.metroToggle5, 0, 0);
      this.tableLayoutPanel5.Controls.Add((Control) this.panel5, 0, 1);
      this.tableLayoutPanel5.Dock = DockStyle.Top;
      this.tableLayoutPanel5.Location = new Point(15, 471);
      this.tableLayoutPanel5.Name = "tableLayoutPanel5";
      this.tableLayoutPanel5.RowCount = 2;
      this.tableLayoutPanel5.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel5.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel5.Size = new Size(548, 45);
      this.tableLayoutPanel5.TabIndex = 87;
      this.metroToggle5.Checked = true;
      this.metroToggle5.CheckState = CheckState.Checked;
      this.metroToggle5.DisplayStatus = false;
      this.metroToggle5.Location = new Point(3, 3);
      this.metroToggle5.Name = "metroToggle5";
      this.metroToggle5.Size = new Size(22, 10);
      this.metroToggle5.Style = MetroColorStyle.System;
      this.metroToggle5.TabIndex = 0;
      this.metroToggle5.Text = "On";
      this.metroToggle5.Theme = MetroThemeStyle.Dark;
      this.metroToggle5.UseSelectable = true;
      this.panel5.AutoSize = true;
      this.panel5.BackColor = Color.White;
      this.panel5.Controls.Add((Control) this.label14);
      this.panel5.Dock = DockStyle.Top;
      this.panel5.Location = new Point(3, 19);
      this.panel5.Name = "panel5";
      this.panel5.Padding = new Padding(3);
      this.panel5.Size = new Size(542, 23);
      this.panel5.TabIndex = 1;
      this.label14.AutoSize = true;
      this.label14.Dock = DockStyle.Top;
      this.label14.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label14.Location = new Point(3, 3);
      this.label14.Name = "label14";
      this.label14.Size = new Size(115, 17);
      this.label14.TabIndex = 2;
      this.label14.Text = "Only new window";
      this.label10.Dock = DockStyle.Top;
      this.label10.ForeColor = SystemColors.ControlDarkDark;
      this.label10.Location = new Point(15, 451);
      this.label10.Name = "label10";
      this.label10.Size = new Size(548, 20);
      this.label10.TabIndex = 86;
      this.label10.Text = "Automatically";
      this.label10.TextAlign = ContentAlignment.MiddleCenter;
      this.metroPanel16.Dock = DockStyle.Top;
      this.metroPanel16.HorizontalScrollbarBarColor = true;
      this.metroPanel16.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel16.HorizontalScrollbarSize = 9;
      this.metroPanel16.Location = new Point(15, 436);
      this.metroPanel16.Name = "metroPanel16";
      this.metroPanel16.Size = new Size(548, 15);
      this.metroPanel16.TabIndex = 81;
      this.metroPanel16.VerticalScrollbarBarColor = true;
      this.metroPanel16.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel16.VerticalScrollbarSize = 10;
      this.tableLayoutPanel6.AutoSize = true;
      this.tableLayoutPanel6.ColumnCount = 1;
      this.tableLayoutPanel6.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel6.Controls.Add((Control) this.metroToggle6, 0, 0);
      this.tableLayoutPanel6.Controls.Add((Control) this.panel6, 0, 1);
      this.tableLayoutPanel6.Dock = DockStyle.Top;
      this.tableLayoutPanel6.Location = new Point(15, 391);
      this.tableLayoutPanel6.Name = "tableLayoutPanel6";
      this.tableLayoutPanel6.RowCount = 2;
      this.tableLayoutPanel6.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel6.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel6.Size = new Size(548, 45);
      this.tableLayoutPanel6.TabIndex = 80;
      this.metroToggle6.DisplayStatus = false;
      this.metroToggle6.Location = new Point(3, 3);
      this.metroToggle6.Name = "metroToggle6";
      this.metroToggle6.Size = new Size(22, 10);
      this.metroToggle6.Style = MetroColorStyle.System;
      this.metroToggle6.TabIndex = 0;
      this.metroToggle6.Text = "Off";
      this.metroToggle6.Theme = MetroThemeStyle.Dark;
      this.metroToggle6.UseSelectable = true;
      this.panel6.AutoSize = true;
      this.panel6.BackColor = Color.White;
      this.panel6.Controls.Add((Control) this.label12);
      this.panel6.Dock = DockStyle.Top;
      this.panel6.Location = new Point(3, 19);
      this.panel6.Name = "panel6";
      this.panel6.Padding = new Padding(3);
      this.panel6.Size = new Size(542, 23);
      this.panel6.TabIndex = 1;
      this.label12.AutoSize = true;
      this.label12.Dock = DockStyle.Top;
      this.label12.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label12.Location = new Point(3, 3);
      this.label12.Name = "label12";
      this.label12.Size = new Size(241, 17);
      this.label12.TabIndex = 2;
      this.label12.Text = "Force to resize non-resizable window";
      this.metroPanel17.Dock = DockStyle.Top;
      this.metroPanel17.HorizontalScrollbarBarColor = true;
      this.metroPanel17.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel17.HorizontalScrollbarSize = 9;
      this.metroPanel17.Location = new Point(15, 376);
      this.metroPanel17.Name = "metroPanel17";
      this.metroPanel17.Size = new Size(548, 15);
      this.metroPanel17.TabIndex = 79;
      this.metroPanel17.VerticalScrollbarBarColor = true;
      this.metroPanel17.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel17.VerticalScrollbarSize = 10;
      this.tableLayoutPanel7.AutoSize = true;
      this.tableLayoutPanel7.ColumnCount = 1;
      this.tableLayoutPanel7.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel7.Controls.Add((Control) this.metroToggle7, 0, 0);
      this.tableLayoutPanel7.Controls.Add((Control) this.panel9, 0, 1);
      this.tableLayoutPanel7.Dock = DockStyle.Top;
      this.tableLayoutPanel7.Location = new Point(15, 308);
      this.tableLayoutPanel7.Name = "tableLayoutPanel7";
      this.tableLayoutPanel7.RowCount = 2;
      this.tableLayoutPanel7.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel7.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel7.Size = new Size(548, 68);
      this.tableLayoutPanel7.TabIndex = 78;
      this.metroToggle7.DisplayStatus = false;
      this.metroToggle7.Location = new Point(3, 3);
      this.metroToggle7.Name = "metroToggle7";
      this.metroToggle7.Size = new Size(22, 10);
      this.metroToggle7.Style = MetroColorStyle.System;
      this.metroToggle7.TabIndex = 0;
      this.metroToggle7.Text = "Off";
      this.metroToggle7.Theme = MetroThemeStyle.Dark;
      this.metroToggle7.UseSelectable = true;
      this.panel9.AutoSize = true;
      this.panel9.BackColor = Color.White;
      this.panel9.Controls.Add((Control) this.metroTrackBar3);
      this.panel9.Controls.Add((Control) this.label8);
      this.panel9.Dock = DockStyle.Top;
      this.panel9.Location = new Point(3, 19);
      this.panel9.Name = "panel9";
      this.panel9.Padding = new Padding(3);
      this.panel9.Size = new Size(542, 46);
      this.panel9.TabIndex = 1;
      this.metroTrackBar3.BackColor = Color.Transparent;
      this.metroTrackBar3.Dock = DockStyle.Top;
      this.metroTrackBar3.Location = new Point(3, 20);
      this.metroTrackBar3.Minimum = 1;
      this.metroTrackBar3.Name = "metroTrackBar3";
      this.metroTrackBar3.Size = new Size(536, 23);
      this.metroTrackBar3.Style = MetroColorStyle.System;
      this.metroTrackBar3.TabIndex = 6;
      this.metroTrackBar3.TabStop = false;
      this.metroTrackBar3.Text = "metroTrackBar3";
      this.metroTrackBar3.Theme = MetroThemeStyle.Dark;
      this.metroTrackBar3.Value = 66;
      this.label8.AutoSize = true;
      this.label8.Dock = DockStyle.Top;
      this.label8.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label8.Location = new Point(3, 3);
      this.label8.Name = "label8";
      this.label8.Size = new Size(152, 17);
      this.label8.TabIndex = 2;
      this.label8.Text = "Window height: [100%]";
      this.metroPanel15.Dock = DockStyle.Top;
      this.metroPanel15.HorizontalScrollbarBarColor = true;
      this.metroPanel15.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel15.HorizontalScrollbarSize = 9;
      this.metroPanel15.Location = new Point(15, 293);
      this.metroPanel15.Name = "metroPanel15";
      this.metroPanel15.Size = new Size(548, 15);
      this.metroPanel15.TabIndex = 77;
      this.metroPanel15.VerticalScrollbarBarColor = true;
      this.metroPanel15.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel15.VerticalScrollbarSize = 10;
      this.tableLayoutPanel4.AutoSize = true;
      this.tableLayoutPanel4.ColumnCount = 1;
      this.tableLayoutPanel4.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel4.Controls.Add((Control) this.metroToggle4, 0, 0);
      this.tableLayoutPanel4.Controls.Add((Control) this.panel4, 0, 1);
      this.tableLayoutPanel4.Dock = DockStyle.Top;
      this.tableLayoutPanel4.Location = new Point(15, 225);
      this.tableLayoutPanel4.Name = "tableLayoutPanel4";
      this.tableLayoutPanel4.RowCount = 2;
      this.tableLayoutPanel4.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel4.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel4.Size = new Size(548, 68);
      this.tableLayoutPanel4.TabIndex = 76;
      this.metroToggle4.DisplayStatus = false;
      this.metroToggle4.Location = new Point(3, 3);
      this.metroToggle4.Name = "metroToggle4";
      this.metroToggle4.Size = new Size(22, 10);
      this.metroToggle4.Style = MetroColorStyle.System;
      this.metroToggle4.TabIndex = 0;
      this.metroToggle4.Text = "Off";
      this.metroToggle4.Theme = MetroThemeStyle.Dark;
      this.metroToggle4.UseSelectable = true;
      this.panel4.AutoSize = true;
      this.panel4.BackColor = Color.White;
      this.panel4.Controls.Add((Control) this.metroTrackBar1);
      this.panel4.Controls.Add((Control) this.label15);
      this.panel4.Dock = DockStyle.Top;
      this.panel4.Location = new Point(3, 19);
      this.panel4.Name = "panel4";
      this.panel4.Padding = new Padding(3);
      this.panel4.Size = new Size(542, 46);
      this.panel4.TabIndex = 1;
      this.metroTrackBar1.BackColor = Color.Transparent;
      this.metroTrackBar1.Dock = DockStyle.Top;
      this.metroTrackBar1.Location = new Point(3, 20);
      this.metroTrackBar1.Minimum = 1;
      this.metroTrackBar1.Name = "metroTrackBar1";
      this.metroTrackBar1.Size = new Size(536, 23);
      this.metroTrackBar1.Style = MetroColorStyle.System;
      this.metroTrackBar1.TabIndex = 6;
      this.metroTrackBar1.TabStop = false;
      this.metroTrackBar1.Text = "metroTrackBar1";
      this.metroTrackBar1.Theme = MetroThemeStyle.Dark;
      this.metroTrackBar1.Value = 66;
      this.label15.AutoSize = true;
      this.label15.Dock = DockStyle.Top;
      this.label15.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label15.Location = new Point(3, 3);
      this.label15.Name = "label15";
      this.label15.Size = new Size(145, 17);
      this.label15.TabIndex = 2;
      this.label15.Text = "Window width: [100%]";
      this.tableLayoutPanel9.AutoSize = true;
      this.tableLayoutPanel9.ColumnCount = 1;
      this.tableLayoutPanel9.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel9.Dock = DockStyle.Top;
      this.tableLayoutPanel9.Location = new Point(15, 225);
      this.tableLayoutPanel9.Name = "tableLayoutPanel9";
      this.tableLayoutPanel9.RowCount = 2;
      this.tableLayoutPanel9.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel9.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel9.Size = new Size(548, 0);
      this.tableLayoutPanel9.TabIndex = 70;
      this.tableLayoutPanel8.AutoSize = true;
      this.tableLayoutPanel8.ColumnCount = 1;
      this.tableLayoutPanel8.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel8.Dock = DockStyle.Top;
      this.tableLayoutPanel8.Location = new Point(15, 225);
      this.tableLayoutPanel8.Name = "tableLayoutPanel8";
      this.tableLayoutPanel8.RowCount = 2;
      this.tableLayoutPanel8.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel8.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel8.Size = new Size(548, 0);
      this.tableLayoutPanel8.TabIndex = 68;
      this.label9.Dock = DockStyle.Top;
      this.label9.ForeColor = SystemColors.ControlDarkDark;
      this.label9.Location = new Point(15, 205);
      this.label9.Name = "label9";
      this.label9.Size = new Size(548, 20);
      this.label9.TabIndex = 49;
      this.label9.Text = "General";
      this.label9.TextAlign = ContentAlignment.MiddleCenter;
      this.metroPanel10.Dock = DockStyle.Top;
      this.metroPanel10.HorizontalScrollbarBarColor = true;
      this.metroPanel10.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel10.HorizontalScrollbarSize = 9;
      this.metroPanel10.Location = new Point(15, 190);
      this.metroPanel10.Name = "metroPanel10";
      this.metroPanel10.Size = new Size(548, 15);
      this.metroPanel10.TabIndex = 41;
      this.metroPanel10.VerticalScrollbarBarColor = true;
      this.metroPanel10.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel10.VerticalScrollbarSize = 10;
      this.tableLayoutPanel2.AutoSize = true;
      this.tableLayoutPanel2.ColumnCount = 1;
      this.tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel2.Controls.Add((Control) this.metroProgressBar1, 0, 2);
      this.tableLayoutPanel2.Controls.Add((Control) this.metroToggle2, 0, 0);
      this.tableLayoutPanel2.Controls.Add((Control) this.panel11, 0, 1);
      this.tableLayoutPanel2.Dock = DockStyle.Top;
      this.tableLayoutPanel2.Location = new Point(15, 120);
      this.tableLayoutPanel2.Name = "tableLayoutPanel2";
      this.tableLayoutPanel2.RowCount = 3;
      this.tableLayoutPanel2.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel2.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel2.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel2.Size = new Size(548, 70);
      this.tableLayoutPanel2.TabIndex = 40;
      this.metroProgressBar1.Dock = DockStyle.Top;
      this.metroProgressBar1.Location = new Point(3, 65);
      this.metroProgressBar1.Name = "metroProgressBar1";
      this.metroProgressBar1.ProgressBarStyle = ProgressBarStyle.Marquee;
      this.metroProgressBar1.Size = new Size(542, 2);
      this.metroProgressBar1.Style = MetroColorStyle.System;
      this.metroProgressBar1.TabIndex = 22;
      this.metroToggle2.Checked = true;
      this.metroToggle2.CheckState = CheckState.Checked;
      this.metroToggle2.DisplayStatus = false;
      this.metroToggle2.Location = new Point(3, 3);
      this.metroToggle2.Name = "metroToggle2";
      this.metroToggle2.Size = new Size(22, 10);
      this.metroToggle2.Style = MetroColorStyle.System;
      this.metroToggle2.TabIndex = 0;
      this.metroToggle2.Text = "On";
      this.metroToggle2.Theme = MetroThemeStyle.Dark;
      this.metroToggle2.UseSelectable = true;
      this.panel11.AutoSize = true;
      this.panel11.BackColor = Color.White;
      this.panel11.Controls.Add((Control) this.label3);
      this.panel11.Controls.Add((Control) this.label4);
      this.panel11.Dock = DockStyle.Top;
      this.panel11.Location = new Point(3, 19);
      this.panel11.Name = "panel11";
      this.panel11.Padding = new Padding(3);
      this.panel11.Size = new Size(542, 40);
      this.panel11.TabIndex = 1;
      this.label3.AutoSize = true;
      this.label3.Dock = DockStyle.Top;
      this.label3.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label3.ForeColor = SystemColors.ControlDarkDark;
      this.label3.Location = new Point(3, 20);
      this.label3.Name = "label3";
      this.label3.Size = new Size(241, 17);
      this.label3.TabIndex = 3;
      this.label3.Text = "window will be centered on sequence";
      this.label4.AutoSize = true;
      this.label4.Dock = DockStyle.Top;
      this.label4.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label4.Location = new Point(3, 3);
      this.label4.Name = "label4";
      this.label4.Size = new Size(123, 17);
      this.label4.TabIndex = 2;
      this.label4.Text = "On Key Sequence";
      this.metroPanel9.Dock = DockStyle.Top;
      this.metroPanel9.HorizontalScrollbarBarColor = true;
      this.metroPanel9.HorizontalScrollbarHighlightOnWheel = false;
      this.metroPanel9.HorizontalScrollbarSize = 9;
      this.metroPanel9.Location = new Point(15, 105);
      this.metroPanel9.Name = "metroPanel9";
      this.metroPanel9.Size = new Size(548, 15);
      this.metroPanel9.TabIndex = 39;
      this.metroPanel9.VerticalScrollbarBarColor = true;
      this.metroPanel9.VerticalScrollbarHighlightOnWheel = false;
      this.metroPanel9.VerticalScrollbarSize = 10;
      this.tableLayoutPanel12.AutoSize = true;
      this.tableLayoutPanel12.ColumnCount = 1;
      this.tableLayoutPanel12.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
      this.tableLayoutPanel12.Controls.Add((Control) this.metroProgressBar5, 0, 2);
      this.tableLayoutPanel12.Controls.Add((Control) this.metroToggle1, 0, 0);
      this.tableLayoutPanel12.Controls.Add((Control) this.panel12, 0, 1);
      this.tableLayoutPanel12.Dock = DockStyle.Top;
      this.tableLayoutPanel12.Location = new Point(15, 35);
      this.tableLayoutPanel12.Name = "tableLayoutPanel12";
      this.tableLayoutPanel12.RowCount = 3;
      this.tableLayoutPanel12.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel12.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel12.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel12.Size = new Size(548, 70);
      this.tableLayoutPanel12.TabIndex = 38;
      this.metroProgressBar5.Dock = DockStyle.Top;
      this.metroProgressBar5.Location = new Point(3, 65);
      this.metroProgressBar5.Name = "metroProgressBar5";
      this.metroProgressBar5.ProgressBarStyle = ProgressBarStyle.Marquee;
      this.metroProgressBar5.Size = new Size(542, 2);
      this.metroProgressBar5.Style = MetroColorStyle.System;
      this.metroProgressBar5.TabIndex = 22;
      this.metroToggle1.Checked = true;
      this.metroToggle1.CheckState = CheckState.Checked;
      this.metroToggle1.DisplayStatus = false;
      this.metroToggle1.Location = new Point(3, 3);
      this.metroToggle1.Name = "metroToggle1";
      this.metroToggle1.Size = new Size(22, 10);
      this.metroToggle1.Style = MetroColorStyle.System;
      this.metroToggle1.TabIndex = 0;
      this.metroToggle1.Text = "On";
      this.metroToggle1.Theme = MetroThemeStyle.Dark;
      this.metroToggle1.UseSelectable = true;
      this.panel12.AutoSize = true;
      this.panel12.BackColor = Color.White;
      this.panel12.Controls.Add((Control) this.label2);
      this.panel12.Controls.Add((Control) this.label7);
      this.panel12.Dock = DockStyle.Top;
      this.panel12.Location = new Point(3, 19);
      this.panel12.Name = "panel12";
      this.panel12.Padding = new Padding(3);
      this.panel12.Size = new Size(542, 40);
      this.panel12.TabIndex = 1;
      this.label2.AutoSize = true;
      this.label2.Dock = DockStyle.Top;
      this.label2.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.ForeColor = SystemColors.ControlDarkDark;
      this.label2.Location = new Point(3, 20);
      this.label2.Name = "label2";
      this.label2.Size = new Size(241, 17);
      this.label2.TabIndex = 3;
      this.label2.Text = "window will be centered automatically";
      this.label7.AutoSize = true;
      this.label7.Dock = DockStyle.Top;
      this.label7.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label7.Location = new Point(3, 3);
      this.label7.Name = "label7";
      this.label7.Size = new Size(91, 17);
      this.label7.TabIndex = 2;
      this.label7.Text = "Automatically";
      this.label1.Dock = DockStyle.Top;
      this.label1.ForeColor = SystemColors.ControlDarkDark;
      this.label1.Location = new Point(15, 15);
      this.label1.Name = "label1";
      this.label1.Size = new Size(548, 20);
      this.label1.TabIndex = 2;
      this.label1.Text = "Services";
      this.label1.TextAlign = ContentAlignment.MiddleCenter;
      this.panel2.Dock = DockStyle.Top;
      this.panel2.Location = new Point(15, 0);
      this.panel2.Name = "panel2";
      this.panel2.Size = new Size(548, 15);
      this.panel2.TabIndex = 106;
      this.linkLabel1.ActiveLinkColor = SystemColors.ControlDark;
      this.linkLabel1.AutoSize = true;
      this.linkLabel1.Dock = DockStyle.Bottom;
      this.linkLabel1.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.linkLabel1.LinkBehavior = LinkBehavior.NeverUnderline;
      this.linkLabel1.LinkColor = Color.White;
      this.linkLabel1.Location = new Point(0, 664);
      this.linkLabel1.Name = "linkLabel1";
      this.linkLabel1.Padding = new Padding(4, 2, 4, 2);
      this.linkLabel1.Size = new Size(176, 21);
      this.linkLabel1.TabIndex = 111;
      this.linkLabel1.TabStop = true;
      this.linkLabel1.Text = "kamilszymborski.github.io";
      this.linkLabel1.VisitedLinkColor = Color.White;
      this.AutoScaleDimensions = new SizeF(9f, 20f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.BackColor = Color.White;
      this.ClientSize = new Size(604, 685);
      this.Controls.Add((Control) this.panel1);
      this.Icon = (System.Drawing.Icon) componentResourceManager.GetObject("$this.Icon");
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = nameof (UI);
      this.ShowIcon = false;
      this.ShowInTaskbar = false;
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = " Window Centering Helper";
      this.panel1.ResumeLayout(false);
      this.panel1.PerformLayout();
      this.metroPanel8.ResumeLayout(false);
      this.metroPanel8.PerformLayout();
      this.metroPanel1.ResumeLayout(false);
      this.metroPanel1.PerformLayout();
      this.panel3.ResumeLayout(false);
      this.panel3.PerformLayout();
      this.panel10.ResumeLayout(false);
      this.panel10.PerformLayout();
      this.panel13.ResumeLayout(false);
      this.panel13.PerformLayout();
      this.tableLayoutPanel3.ResumeLayout(false);
      this.tableLayoutPanel3.PerformLayout();
      this.panel8.ResumeLayout(false);
      this.panel8.PerformLayout();
      this.tableLayoutPanel10.ResumeLayout(false);
      this.tableLayoutPanel10.PerformLayout();
      this.panel7.ResumeLayout(false);
      this.panel7.PerformLayout();
      this.tableLayoutPanel5.ResumeLayout(false);
      this.tableLayoutPanel5.PerformLayout();
      this.panel5.ResumeLayout(false);
      this.panel5.PerformLayout();
      this.tableLayoutPanel6.ResumeLayout(false);
      this.tableLayoutPanel6.PerformLayout();
      this.panel6.ResumeLayout(false);
      this.panel6.PerformLayout();
      this.tableLayoutPanel7.ResumeLayout(false);
      this.tableLayoutPanel7.PerformLayout();
      this.panel9.ResumeLayout(false);
      this.panel9.PerformLayout();
      this.tableLayoutPanel4.ResumeLayout(false);
      this.tableLayoutPanel4.PerformLayout();
      this.panel4.ResumeLayout(false);
      this.panel4.PerformLayout();
      this.tableLayoutPanel2.ResumeLayout(false);
      this.tableLayoutPanel2.PerformLayout();
      this.panel11.ResumeLayout(false);
      this.panel11.PerformLayout();
      this.tableLayoutPanel12.ResumeLayout(false);
      this.tableLayoutPanel12.PerformLayout();
      this.panel12.ResumeLayout(false);
      this.panel12.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
